### ISSUE TITLE
IEEE 830 2.3 Restricciones

### ISSUE THREAD

**Issue by rosrob** [rosrob/TecnoXpress#10]
Completar en el documento el punto 2.3. 

_Interfaz para ser usada con internet (solamente o puede ser de escritorio).
Lenguajes y tecnologías en uso: HTML, JavScript…….._

**Comment by Francovega** [comment]
Restricciones

Interfaz para ser usada con internet.
Lenguajes y tecnologías en uso: HTML, CSS, Java Script y Python.
Librerías: Bootstrap.
Los servidores deben ser capaces de atender consultas concurrentemente.
El sistema se diseñará según un modelo cliente/servidor.
El sistema deberá tener un diseño e implementación sencilla
