### ISSUE TITLE
Diseñar logo y definir colores para la web 

### ISSUE THREAD

**Issue by rosrob** [rosrob/TecnoXpress#13]
Diseñar el logo y definir paleta de colores. Al cerrar la issues responder /cometar cargando imagen del logo y los códigos de los colores utilizados.

**Comment by Burenyu** [comment]
/cometar
Naranja :#DA5000
Gris: #494949
Negro: #000000
Blanco: #FFFFFF
![Logo](https://github.com/rosrob/TecnoXpress/assets/142270256/41f0ff1c-b89b-4e63-8c6f-479954af19d8)
