### ISSUE TITLE
IEEE 830 1.1 Propósito

### ISSUE THREAD

**Issue by rosrob** [rosrob/TecnoXpress#2]
Completar el proposito del documento IEEE

	El presente documento tiene como propósito definir las especificaciones funcionales, para el desarrollo de un sistema de información web que permitirá …………..

**Comment by RominaTejeda** [comment]
El presente documento tiene como propósito definir en forma clara y detallada todos los requisitos y especificaciones necesarias para el desarrollo de una tienda virtual de productos tecnológicos.  El informe va orientado a los integrantes del grupo de desarrollo de la tienda y a usuarios de la misma.
