### ISSUE TITLE
#US09 Footer

### ISSUE THREAD

**Issue by rosrob** [rosrob/TecnoXpress#27]
Realiza footer con:
- [x] Iconos de redes sociales- SEGUINOS
- [x] Iconos de MEDIOS DE PAGO
- [x] Enlace a CONTACTO e iconos.
- [x] Terminos y condiciones

**Comment by STulian23** [comment]
Footer realizado 
<footer class="PIEDEPAGINA">
          <div class="grupo-1">
              <div class="box">
                  <div class="logo">
                      <img src="media/logo.png" alt="">
                  </div>
              </div>
              <div class="box">
                <div class="info">
                    <h2>ATENCION AL CLIENTE</h2>
                    <p>0810-555-8894</p>
                    <p>consultas@tecnoxpress.com.ar</p>
                    <p> Lunes a viernes de 8 a 20hs.</p>
                    <p> Sabado de 8 a 14hs</p> 
                 </div>
            </div>
            
            <div class="box">
              <h2>SIGUENOS</h2>
              <div class="redes">      
                <a href="https://www.facebook.com/" target="_blank"><span class="fb"><i class="fa-brands fa-facebook-f"></i></i></span></a>
                <a href="https://twitter.com/" target="_blank"><span class="tw"><i class="fa-brands fa-x-twitter"></i></i></span></a>
                <a href="https://www.instagram.com/" target="_blank"><span class="insta"><i class="fa-brands fa-instagram"></i></i></span></a>
                <a href="https://www.tiktok.com/" target="_blank"><span class="tk"><i class="fa-brands fa-tiktok"></i></span></a>  
              </div>
            </div>
            <div class="box">
              <h2>MEDIOS DE PAGO</h2>
              <a href="https://www.visa.com/" target="_blank"><span class="vi"><i class="fa-brands fa-cc-visa"></i></span></a>
              <a href="https://www.mastercard.com/" target="_blank"><span class="ms"><i class="fa-brands fa-cc-mastercard"></i></span></a>
              <a href="https://www.americanexpress.com/" target="_blank"><span class="amx"><i class="fa-brands fa-cc-amex"></i></span></a>
              <a href="https://www.paypal.com/" target="_blank"><span class="pay"><i class="fa-brands fa-cc-paypal"></i></span></a>  
            <a href="https://academy.binance.com/" target="_blank"><span class="btc"><i class="fa-brands fa-btc"></i></span></a>
            </div>
            <div class="box">
              <h2>CONTACTO</h2>
              <a href="https://api.whatsapp.com/send?phone=[número de teléfono]" target="_blank"><span class="wsp"><i class="fa-brands fa-whatsapp"></i></span></a>
              <a href="mailto:consultas@tecnoxpress.com.ar"><span class="mail"><i class="fa-sharp fa-solid fa-at"></i></span></a>
            </div>
                              
          </div>
          <div class="grupo-2">
              <small>&copy; 2023 <b> TECNOXPRESS</b> - Todos los Derechos Reservados.</small>
  
          </div>
  
      </footer>
