### ISSUE TITLE
IEEE 830 1.4 Definiciones, acrónimos y abreviaturas

### ISSUE THREAD

**Issue by rosrob** [rosrob/TecnoXpress#5]
Completar el cuadro 1.4 del documento IEEE 380

**Comment by STulian23** [comment]
El usuario podrá: 
Navegar por los productos: podrías explorar los productos disponibles en la página web y buscar aquellos que te interesen.
Realizar compras: podrías agregar productos a tu carrito de compras y completar el proceso de pago para realizar una compra.
Ver el historial de compras: podrías ver un registro de tus compras anteriores en la página web.
Buscar soporte técnico: si tienes problemas con un producto que compraste en la página web, podrías buscar soporte técnico o ponerse en contacto con el servicio al cliente.
Crear una cuenta: podrías crear una cuenta en la página web para acceder a funciones adicionales, como guardar tus datos de envío y facturación para compras futuras.
Moodle: Tienda Virtual
