### ISSUE TITLE
IEEE 830 1.5 Referencias

### ISSUE THREAD

**Issue by rosrob** [rosrob/TecnoXpress#6]
Completar el punto 1.5 Referencias del documento

**Comment by STulian23** [comment]
Standard IEEE 830 - 1998 | IEEE
En este documento se da a conocer el funcionamiento de “TECNOXPRESS”.
Tienda virtual de venta de accesorios electrónicos.
Se llevará a cabo a través de explicaciones escritas, en donde se detallarán funcionalidades, datos requeridos, definiciones.
Se expondrán también diferentes secciones de este sitio, donde se podrá ver fácilmente sus productos, características, medios de pago, contacto, envío, entre otras.
Todo esto con el fin de visualizar de forma general - y específica - cómo va a funcionar el sitio al momento que clientes y encargados interactúen con ella.
